export const IMAGES = {
  homeActive: require('./home-active.png'),
  homeInactive: require('./home-inactive.png'),
  settingsActive: require('./settings-active.png'),
  settingsInactive: require('./settings-inactive.png'),
  bookOpenActive: require('./book-open-active.png'),
  bookOpenInactive: require('./book-open-inactive.png'),
  smile: require('./smile.png'),
  back: require('./back.png'),
  right: require('./right.png'),
  monthLeft: require('./month-left.png'),
  monthRight: require('./month-right.png'),
  more: require('./more.png'),
  xmark: require('./xmark.png'), 
  backup: require('./backup.png'), 
  feedbackChat: require('./feedback-chat.png'), 
}