# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!
use_modular_headers!

# Configure frameworks linkage; default to static if USE_FRAMEWORKS is not set
linkage = ENV['USE_FRAMEWORKS'] || 'static'
Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
use_frameworks! :linkage => linkage.to_sym

require_relative '../node_modules/react-native-permissions/scripts/setup'

setup_permissions([
  'Notifications',
])

target 'MoodlyFrontend' do
  config = use_native_modules!

  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'GTMSessionFetcher/Core', '~> 3.4'

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # React Native default post install script
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => true
    )
  end
end
