def node_require(script)
  Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

require node_require('react-native/scripts/react_native_pods.rb')
require node_require('react-native-permissions/scripts/setup.rb')

platform :ios, '15.1'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS'] || 'static'
use_frameworks! :linkage => linkage.to_sym

target 'Moodly' do
  config = use_native_modules!

  setup_permissions([
    'Notifications',
  ]);

  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'GTMSessionFetcher/Core', '~> 3.4'

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
